#pragma once
#include "a2ext_pins.h"
#define CONFIG_SYSCLOCK 126.0
#define CONFIG_PIN_HSYNC A2EXT_GPIO_VGA_HSYNC
#define CONFIG_PIN_VSYNC A2EXT_GPIO_VGA_VSYNC
#define CONFIG_PIN_RGB_BASE A2EXT_GPIO_VGA_R0
#define CONFIG_VGA_PIO pio1
#define CONFIG_VGA_SPINLOCK_ID 31
