#!/usr/bin/env python3
"""Validate the carrier pin contract and emit the firmware header."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "fw/a2ext-lib/include/a2ext_pins.h"


def validate(pins):
    bus = pins["bus"]
    assert len(bus) == 33, "Apple II interface must contain 33 signals"
    assert len({p["signal"] for p in bus}) == 33, "duplicate bus signal"
    assert len({p["slot"] for p in bus}) == 33, "duplicate slot contact"
    used = [p["gpio"] for p in bus] + list(pins["uart"].values()) + pins["daughter_gpios"]
    assert sorted(used) == list(range(48)), "GPIO collision or missing GPIO"
    by_name = {p["signal"]: p for p in bus}
    for bit in range(16):
        assert by_name[f"A{bit}"]["slot"] == 2 + bit
        assert by_name[f"A{bit}"]["gpio"] == 2 + bit
    for bit in range(8):
        assert by_name[f"D{bit}"]["slot"] == 49 - bit
        assert by_name[f"D{bit}"]["gpio"] == 18 + bit
    assert max(p["gpio"] for p in bus) < 40, "5 V bus on ADC pad"
    assert all(by_name[n]["gpio"] < 32 for n in
               ("RWB", "DEVSEL_N", "IOSEL_N", "IOSTRB_N", "PHI0", "RES_N"))
    assert by_name["IRQ_N"]["direction"] == "open_drain"
    assert by_name["NMI_N"]["direction"] == "open_drain"
    idc = pins["idc"]
    assert [p["pin"] for p in idc] == list(range(1, 21))
    assert [p["gpio"] for p in idc if "gpio" in p] == [0, 1] + list(range(35, 48))
    assert {p["pin"]: p["signal"] for p in idc if "gpio" not in p} == {
        16: "GND", 17: "+3V3", 18: "RUN_N", 19: "+5V_DB", 20: "GND"}
    for mode in ("vga", "dvi"):
        signals = pins[mode]
        assert len(set(signals.values())) == len(signals), f"duplicate {mode} GPIO"
        assert set(signals.values()) <= set(pins["daughter_gpios"])
    for name in ("D0", "D1", "D2", "CLK"):
        assert pins["dvi"][name + "_P"] % 2 == 0
        assert pins["dvi"][name + "_N"] == pins["dvi"][name + "_P"] + 1


def header(pins):
    lines = ["/* Generated by tools/pinout.py from hw/pinout.json. */", "#pragma once", ""]
    for pin in pins["bus"]:
        lines.append(f'#define A2EXT_GPIO_{pin["signal"]} {pin["gpio"]}u')
    for name, gpio in pins["uart"].items():
        lines.append(f"#define A2EXT_GPIO_UART_{name} {gpio}u")
    for mode in ("vga", "dvi"):
        for name, gpio in pins[mode].items():
            lines.append(f"#define A2EXT_GPIO_{mode.upper()}_{name} {gpio}u")
    lines += ["#define A2EXT_GPIO_ADDR_BASE A2EXT_GPIO_A0",
              "#define A2EXT_GPIO_DATA_BASE A2EXT_GPIO_D0", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate firmware header")
    args = parser.parse_args()
    pins = json.loads((ROOT / "hw/pinout.json").read_text())
    validate(pins)
    expected = header(pins)
    if args.write:
        HEADER.parent.mkdir(parents=True, exist_ok=True)
        HEADER.write_text(expected)
    else:
        assert HEADER.read_text() == expected, "stale header; run tools/pinout.py --write"
    print("Pin contract OK: 33 bus + 2 UART + 13 daughterboard GPIOs; no collisions")


if __name__ == "__main__":
    main()
